fa3

diff --git a/.github/workflows/build_linux.yml b/.github/workflows/build_linux.yml
--- a/.github/workflows/build_linux.yml
+++ b/.github/workflows/build_linux.yml
@@ -78,13 +78,30 @@ jobs:
           NVCC_THREADS: 2
         run: |
           chmod +x build_linux.sh
-          ./build_linux.sh ${{ inputs.flash-attn-version }} ${{ inputs.python-version }} ${{ inputs.torch-version }} ${{ inputs.cuda-version }}
+          ./build_linux.sh ${{ inputs.flash-attn-version }} ${{ inputs.python-version }} ${{ inputs.torch-version }} ${{ inputs.cuda-version }} false
           wheel_name=$(basename $(ls flash-attention/dist/*.whl | head -n 1))
           echo "WHEEL_NAME=$wheel_name" >> $GITHUB_OUTPUT
+
+
+      - name: Build wheels for FA3
+        id: build_wheels_fa3
+        env:
+          MAX_JOBS: 2
+          NVCC_THREADS: 2
+        run: |
+          chmod +x build_linux.sh
+          ./build_linux.sh ${{ inputs.flash-attn-version }} ${{ inputs.python-version }} ${{ inputs.torch-version }} ${{ inputs.cuda-version }} true
+          wheel_name=$(basename $(ls hopper/dist/*.whl | head -n 1))
+          echo "WHEEL_NAME_FA3=$wheel_name" >> $GITHUB_OUTPUT
 
       - name: Install Test
         run: |
           pip install --no-cache-dir flash-attention/dist/${{ steps.build_wheels.outputs.WHEEL_NAME }}
+          python -c "import flash_attn; print(flash_attn.__version__)"
+      
+      - name: Install Test for FA3
+        run: |
+          pip install --no-cache-dir hopper/dist/${{ steps.build_wheels_fa3.outputs.WHEEL_NAME_FA3 }}
           python -c "import flash_attn; print(flash_attn.__version__)"
 
       - name: Upload Release Asset
@@ -102,3 +119,12 @@ jobs:
 
           # Upload the release asset using GitHub CLI
           gh release upload "$tag_name" "$wheel_path" --clobber
+
+          wheel_path_fa3="hopper/dist/${{ steps.build_wheels_fa3.outputs.WHEEL_NAME_FA3 }}"
+          if [ ! -f "$wheel_path_fa3" ]; then
+            echo "Error: Wheel file not found at $wheel_path_fa3"
+            exit 1
+          fi
+
+          # Upload the release asset using GitHub CLI
+          gh release upload "$tag_name" "$wheel_path_fa3" --clobber
